// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOdw0jk3WlmDgg-z1JpvXOBOzR1fQ_Q5Q',
    appId: '1:456996745091:web:c8cafbb2b11599196f10b6',
    messagingSenderId: '456996745091',
    projectId: 'vending-app-dynamic-link',
    authDomain: 'vending-app-dynamic-link.firebaseapp.com',
    storageBucket: 'vending-app-dynamic-link.appspot.com',
    measurementId: 'G-PXE24GG56N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDo4yUtVWeVD_FkkkkjiaL4vnyXZgmbaY',
    appId: '1:456996745091:android:e10937ee392a48316f10b6',
    messagingSenderId: '456996745091',
    projectId: 'vending-app-dynamic-link',
    storageBucket: 'vending-app-dynamic-link.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZPRVmgrpQ69k5HNk2WLwa88I1ZXSkiZM',
    appId: '1:456996745091:ios:a83c8a8f765b3e9d6f10b6',
    messagingSenderId: '456996745091',
    projectId: 'vending-app-dynamic-link',
    storageBucket: 'vending-app-dynamic-link.appspot.com',
    iosClientId: '456996745091-j0sdbs2qud3ul6p8lqlahfnhcm1rukpf.apps.googleusercontent.com',
    iosBundleId: 'com.example.vendingAppPoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZPRVmgrpQ69k5HNk2WLwa88I1ZXSkiZM',
    appId: '1:456996745091:ios:3e6f5b71b53524a76f10b6',
    messagingSenderId: '456996745091',
    projectId: 'vending-app-dynamic-link',
    storageBucket: 'vending-app-dynamic-link.appspot.com',
    iosClientId: '456996745091-iu6gl2gc2pno9lc8t9cvg1knb4vf8p3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.vendingAppPoc.RunnerTests',
  );
}
